name: Gradle Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Gradle Build
      run: ./gradlew build test site
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: build/site
